/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Password;
import com.sun.org.apache.xerces.internal.impl.dtd.models.CMBinOp;
import javax.swing.JOptionPane;

/**
 *
 * @author jaime
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Password c = null;

    public Principal() {
        initComponents();
        cmdMostrar.setEnabled(false);
        cmdCambiar.setEnabled(false);
        cmdComprobarSeguridad.setEnabled(false);
        cmdGuardar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        cmdGuardar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        cmdMostrar = new javax.swing.JButton();
        cmdCambiar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        cmdComprobarSeguridad = new javax.swing.JButton();
        cmdCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PASSWORDS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos:"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 100, -1));

        jLabel2.setText("Contraseña");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 230, 110));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Mostrar:"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMostrar.setEditable(false);
        txtMostrar.setColumns(20);
        txtMostrar.setRows(5);
        jScrollPane1.setViewportView(txtMostrar);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 210, 120));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 230, 150));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Opciones:"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdMostrar.setText("Mostrar"); // NOI18N
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 160, 30));

        cmdCambiar.setText("Cambiar contraseña");
        cmdCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCambiarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 160, 30));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, 30));

        cmdComprobarSeguridad.setText("Comprobar la seguridad");
        cmdComprobarSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdComprobarSeguridadActionPerformed(evt);
            }
        });
        jPanel4.add(cmdComprobarSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 213, 160, 30));

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel4.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 43, 160, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 200, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(516, 363));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        txtMostrar.setText("");
        txtMostrar.setText("Su contraseña es: " + txtContraseña.getText());
        cmdMostrar.setEnabled(false);
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        if (txtContraseña.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite por favor la contraseña");
            txtContraseña.requestFocusInWindow();
        } else if (txtContraseña.getText().length() < 6) {
            JOptionPane.showMessageDialog(this, "La contraseña debe tener minimo 6 caracteres");
            txtContraseña.requestFocusInWindow();
        } else {
            try {
                JOptionPane.showMessageDialog(this, "Contraseña creada correctamente");
                cmdCambiar.setEnabled(true);
                cmdComprobarSeguridad.setEnabled(true);
                cmdCrear.setEnabled(false);
                cmdMostrar.setEnabled(true);
                String contraseña = txtContraseña.getText();
                Password c = new Password(contraseña);
            } catch (NullPointerException e) {
            }
        }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCambiarActionPerformed

        int op = JOptionPane.showConfirmDialog(this, "¿Seguro que desea Cambiar su contraseña?", "¿?", JOptionPane.YES_OPTION);

        if (op == JOptionPane.YES_OPTION) {
            txtContraseña.setText("");
            txtMostrar.setText("");
            JOptionPane.showMessageDialog(this, "Digite por favor su nueva contraseña");
            txtContraseña.requestFocusInWindow();
            cmdGuardar.setEnabled(true);
            cmdCambiar.setEnabled(false);
            cmdComprobarSeguridad.setEnabled(false);
            cmdMostrar.setEnabled(false);

        } else {

        }

    }//GEN-LAST:event_cmdCambiarActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        if (txtContraseña.getText().length() < 6) {
            JOptionPane.showMessageDialog(this, "La contraseña debe tener minimo 6 caracteres");
            txtContraseña.requestFocusInWindow();
        } else {
            txtContraseña.setText(txtContraseña.getText());
            JOptionPane.showMessageDialog(this, "Contraseña cambiada correctamente");
            cmdCambiar.setEnabled(true);
            cmdComprobarSeguridad.setEnabled(true);
            cmdMostrar.setEnabled(true);
            cmdGuardar.setEnabled(false);
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed

        txtContraseña.setText("");
        txtMostrar.setText("");
        txtContraseña.requestFocusInWindow();

        cmdCrear.setEnabled(true);
        cmdCambiar.setEnabled(false);
        cmdComprobarSeguridad.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdGuardar.setEnabled(false);

    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdComprobarSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdComprobarSeguridadActionPerformed
        if (txtContraseña.getText().length() <= 8) {
            JOptionPane.showMessageDialog(this, "Su contraseña es debil con "+txtContraseña.getText().length()+" carateres");
        } else {
            JOptionPane.showMessageDialog(this, "Su contraseña es fuerte con "+txtContraseña.getText().length()+" carateres");
        }
    }//GEN-LAST:event_cmdComprobarSeguridadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCambiar;
    private javax.swing.JButton cmdComprobarSeguridad;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextArea txtMostrar;
    // End of variables declaration//GEN-END:variables
}
